### ISSUE TITLE
RTL divider not showing in Grid view

### ISSUE THREAD

**Issue by samrakchan** [Fondesa/RecyclerViewDivider#14]
Divider now working in RTL while using GridLayoutManager.

**Comment by Fondesa** [comment]
@samrakchan Actually this library doesn't support RTL. The RTL support will be released within the 2.0.0 version because there'll be some breaking changes.

**Comment by Fondesa** [comment]
Resolved in 4b29d835db9d35f33770fa682191cfb64bf8c61e
