### ISSUE TITLE
Bug: using default divider style in class that extends Application doesn't work well for dark theme

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Fondesa/RecyclerViewDivider#43]
Attached sample project and video to show the issue.

The video shows before and after using the Application class.

For now, the only workaround is to do it manually, or maybe use something like this nice extension function:
```kt
fun RecyclerView.setDefaultDividers() {
    val context = this.context
    context.obtainStyledAttributes(intArrayOf(android.R.attr.listDivider)).use { typedArray ->
        typedArray.getDrawable(0)
            ?.let { RecyclerViewDivider.with(context).hideLastDivider().drawable(it).build().addTo(this) }
    }
}

```
[My Application.zip](https://github.com/Fondesa/RecyclerViewDivider/files/3827710/My.Application.zip)
[2019-11-09_22-25-44.zip](https://github.com/Fondesa/RecyclerViewDivider/files/3827711/2019-11-09_22-25-44.zip)

**Comment by AndroidDeveloperLB** [comment]
I actually think the default one should hide the last divider. Weird that the library didn't set it as such.

**Comment by Fondesa** [comment]
Found the problem. It's related to the implementation of the method `obtainStyledAttributes()` which access `getTheme()`. The implementation of `getTheme()` is different between `Application` and `Activity`. That's why it wasn't working.
You can change the implementation of `provideDividerBuilder()` from this:
```kotlin
val result = RecyclerViewDivider.Builder(context)
obtainStyledAttributes(intArrayOf(android.R.attr.listDivider)).use { typedArray ->
    typedArray.getDrawable(0)?.let { result.drawable(it) }
}
return result
```

To this:
```kotlin
val result = RecyclerViewDivider.Builder(context)
// Invoke it on the Activity instead of the Application.
context.obtainStyledAttributes(intArrayOf(android.R.attr.listDivider)).use { typedArray ->
    typedArray.getDrawable(0)?.let { result.drawable(it) }
}
return result
```

**Comment by Fondesa** [comment]
And BTW yes, I think the `hideLastDivider()` could become the default visibility. I didn't make it as default only following the theory "the default is most basic implementation", but I should have reasoned with "the default is the most common usage".

**Comment by AndroidDeveloperLB** [comment]
Why would the default be the basic implementation?
Also, you said I can call the default theming on the application class. Not on the Activity.
Now it's even more important to ditch the option to put it on the application class, and use more commonly used ways, like for Views.

There was actually a talk about Context by Google developers, when ApplicationContext isn't the good choice and that you should try to use the one of the Activity when possible.

**Comment by Fondesa** [comment]
> Why would the default be the basic implementation?

Cause I did this library 3 years ago and I thought it was a good choice, now I can see it's a mistake.

> Also, you said I can call the default theming on the application class. Not on the Activity.

I said the library checks if the `Application` implements `RecyclerViewDivider.BuilderProvider` to pick the default configuration and I also said the `Context` passed in the method is the same of the in-place call of `RecyclerViewDivider.with(Context)`, so in your case, the `Activity`.
If that wasn't clear, it can be I wasn't understood before.

> Now it's even more important to ditch the option to put it on the application class, and use more commonly used ways, like for Views.
There was actually a talk about Context by Google developers, when ApplicationContext isn't the good choice and that you should try to use the one of the Activity when possible.

I haven't any other idea to give the user the possibility to specify a common dynamic configuration for all the dividers of the app if not using an interface on the `Application`. I'll add the theme attributes for a basic common customization, but they won't solve cases like:

```kotlin
RecyclerViewDivider.with(this)
    .drawableManager(object : DrawableManager {
        override fun itemDrawable(groupCount: Int, groupIndex: Int): Drawable {
            val color = if (groupCount % 2 == 0) Color.BLACK else Color.RED
            return ColorDrawable(color)
        }
    })
    .build()
```

**Comment by AndroidDeveloperLB** [comment]
I don't understand. You can provide both. If the user doesn't set a drawable, the default one is what you can have from the system.
After all, you already chose a default one...

Anyway, please just think about it. I think you can reach something like what Android provides for Views, attributes, and styles, while also allowing to customize at runtime.

**Comment by Fondesa** [comment]
With: 
> I'll add the theme attributes for a basic common customization, but they won't solve cases like [...]

I meant to say that I'll use both, but that I can't remove the `RecyclerViewDivider.BuilderProvider`.

**Comment by AndroidDeveloperLB** [comment]
So you want to support 3 things that can override...
I think you are going too far. Could complicate things...

**Comment by Fondesa** [comment]
I have to think a bit if that's too far or not. BTW the theme attributes will be added anyway.

**Comment by AndroidDeveloperLB** [comment]
OK. I guess you are right. Sorry.

**Comment by Fondesa** [comment]
No problem at all, your help is appreciated and the ideas we discussed about in the two issues are added to the milestone 4.x.
So thanks again, if anything else comes to your mind, don't hesitate to comment or open other issues.

**Comment by Fondesa** [comment]
BTW I'm closing this issue since it can be solved using `context.obtainStyledAttributes()`. Check the milestone [4.x](https://github.com/Fondesa/RecyclerViewDivider/milestone/2) for what we've discussed about.

**Comment by AndroidDeveloperLB** [comment]
I don't understand what you mean. 
Please consider using default style for dividers.

**Comment by Fondesa** [comment]
I meant only to move this conversation to the related issues: #45 and #46 
I'll implement all of this, just move the conversation on those issues since I'll refer to them for the milestone.

**Comment by AndroidDeveloperLB** [comment]
Oh ok.

**Comment by fondesa** [comment]
Just released the version [3.2.0](https://github.com/fondesa/recycler-view-divider/releases/tag/3.2.0) which uses `android:listDivider` by default to get the divider's `Drawable` and other theme attributes ([wiki](https://github.com/fondesa/recycler-view-divider/wiki/usage).

**Comment by fondesa** [comment]
It also hides the last divider by default.

**Comment by AndroidDeveloperLB** [comment]
And in code, like this:

```kt
RecyclerViewDivider.with(context).addTo(this) 
```

Meaning no need for this:

```kt
fun RecyclerView.setDefaultDividers() {
    val context = this.context
    context.obtainStyledAttributes(intArrayOf(android.R.attr.listDivider)).use { typedArray ->
        typedArray.getDrawable(0)
                ?.let { RecyclerViewDivider.with(context).drawable(it).hideLastDivider().build().addTo(this) }
    }
}
```
?
