### ISSUE TITLE
[Suggestion] Each item's divider has same size

### ISSUE THREAD

**Issue by kjsolo** [fondesa/RecyclerViewDivider#47]
Make each item's divider has same size, this is good for use **ConstraintLayout's layout_constraintDimensionRatio**. Otherwise, the height of each item is inconsistent
such as:
```xml
<ConstraintLayout>
    <View app:layout_constraintDimensionRatio="1:1" />
</ConstraintLayout>
```
```kotlin
val left = (lineAccumulatedSpan - 1) * size / spanCount
val right = size - lineAccumulatedSpan * size / spanCount
when {
    // LinearLayoutManager or GridLayoutManager with 1 column
    spanCount == 1 || spanSize == spanCount -> setRect(0, 0, 0, size)
    // first element in the group
    lineAccumulatedSpan == spanSize -> setRect(left, 0, right, size)
    // last element in the group
    lineAccumulatedSpan == spanCount -> setRect(left, 0, right, size)
    // element in the middle
    else -> setRect(left, 0, right, size)
}
```
sample:
column: 3,
divider size: 26px
your code: [0-13] [13-13] [13-0]
my code: [0-18] [8-9] [17-0]

**Comment by Fondesa** [comment]
I'm sorry but I've not understood the suggestion. Can you explain it clearer please?

**Comment by fondesa** [comment]
Since some time passed, I'm closing it until you won't provide any additional information. Feel free to re-open it in case.
