### ISSUE TITLE
Hope to support one direction margin setting , like marginLeft

### ISSUE THREAD

**Issue by UsherBaby** [Fondesa/RecyclerViewDivider#6]

**Comment by Fondesa** [comment]
That could be nice. I have to figure out how to implement this.
If you have any idea, you can submit a PR, otherwise, I'll implement it as soon as possible.

**Comment by Sforllln** [comment]
I think it should be the case

**Comment by blackberry2016** [comment]
@Fondesa Is that under developing now ?

**Comment by Fondesa** [comment]
@blackberry2016 Not for now, I'm busy with other projects actually. Obviously if you want to contribute, you can!

**Comment by Fondesa** [comment]
@blackberry2016 @UsherBaby @Sforllln This is under developing now.

**Comment by UsherBaby** [comment]
@Fondesa Greate work.

**Comment by Fondesa** [comment]
Example of inset applied before (for the vertical list) and after (for the horizontal list)

<img src="https://user-images.githubusercontent.com/13958744/32023089-91c6e60e-b9d8-11e7-9c5f-dacdf62e2ee9.png" height="500">

**Comment by Fondesa** [comment]
The inset is now available with the version **1.4.0**.
You can add an inset using the method `inset(int, int)` or using the method `insetManager(InsetManager)` that is more flexible.
Check the doc for further explanations.
