### ISSUE TITLE
hideFirstDivider(); changeDividerColor(int postion,int color);

### ISSUE THREAD

**Issue by JustinChiang123** [fondesa/RecyclerViewDivider#62]
### Description

Hide the first line-->hideFirstDivider();
Change the color of the line-->changeDividerColor(int postion,int color);

**Comment by fondesa** [comment]
You can already achieve that result using `VisibilityManager` and `DrawableManager`:
```kotlin
```

**Comment by fondesa** [comment]
If you have other doubts, don't hesitate to re-open the issue.
