### ISSUE TITLE
Errors occur-ed while running your project library.

### ISSUE THREAD

**Issue by Puneethsai** [Fondesa/RecyclerViewDivider#7]
cannot resolve method with(),addTo(),removeFrom(). I had included gradle also. Can you please explain what is error.

**Comment by Fondesa** [comment]
I can run the project successfully also deleting the cache. 
1. Can you post here the build stacktrace?
2. Are you compiling against localDebug?

**Comment by Puneethsai** [comment]
![console](https://user-images.githubusercontent.com/15609726/28908232-2aa30b6c-7840-11e7-9b53-5d75e0b42f9a.PNG)
![gradle](https://user-images.githubusercontent.com/15609726/28908234-2ae4ecbc-7840-11e7-8afb-0d344f976260.PNG)
![gradle_error](https://user-images.githubusercontent.com/15609726/28908235-2ae9789a-7840-11e7-8363-a3a82cd3e3f0.PNG)

**Comment by Fondesa** [comment]
As written in the release notes of the version [1.3.0](https://github.com/Fondesa/RecyclerViewDivider/releases/tag/1.3.0), you must build the divider before adding it to the `RecyclerView`. 
Example: `RecyclerViewDivider.with(context).build().addTo(recyclerView)`

**Comment by Fondesa** [comment]
@Puneethsai Was the issue solved?

**Comment by Puneethsai** [comment]
Thank you @Fondesa. Solved!!
