### ISSUE TITLE
Re-adds divider on refresh

### ISSUE THREAD

**Issue by DaveMurchison83** [Fondesa/RecyclerViewDivider#8]
Can you create a method of removing itemdecoration on pull to refresh? Currently when a recyclerview is refreshed it adds the divider along with the existing one.

**Comment by Fondesa** [comment]
@DaveMurchison83 Can you post here some code demonstrating how you are using the divider?

**Comment by DaveMurchison83** [comment]
Sure.

Very simply, after setting the recyclerview adapter, I call your code:

```
                            mRecyclerView.setAdapter(adapter);

                            RecyclerViewDivider.with(rootView.getContext())
                                    .color(rootView.getContext().getResources().getColor(R.color.listDivide))
                                    .hideLastDivider()
                                    .build()
                                    .addTo(mRecyclerView);
```

When I use pull to refresh, it clears the recyclerview but the divider isn't cleared, so when the recyclerview is populated again, it adds a second divider under each item.

If I use the official Android method of adding dividers, it works:

```
                            mRecyclerView.setAdapter(adapter);

                            mRecyclerView.removeItemDecoration(itemDecorator);

                            itemDecorator = new DividerItemDecoration(mRecyclerView.getContext(),
                                    linearLayoutManager.getOrientation());
                            mRecyclerView.addItemDecoration(itemDecorator);

                            itemDecorator.setDrawable(ContextCompat.getDrawable(context, R.drawable.divider));
```


So it looks to me that by calling **removeItemDecoration** before setting a divider would work.

**Comment by Fondesa** [comment]
Actually, you can remove the `RecyclerViewDivider` as you are doing with the Android method.
You can do it using the method below in `RecyclerViewDivider` class:

```java
void removeFrom(@NonNull RecyclerView recyclerView)
```

So, taking your example changing the `DividerItemDecoration` to `RecyclerViewDivider`, the result is:

```java
divider.removeFrom(mRecyclerView);

mRecyclerView.setAdapter(adapter);

divider = RecyclerViewDivider.with(rootView.getContext())
        .color(rootView.getContext().getResources().getColor(R.color.listDivide))
        .hideLastDivider()
        .build();

divider.addTo(mRecyclerView);
```

**Comment by Fondesa** [comment]
@DaveMurchison83 If the issue is solved, can you close it?

**Comment by Fondesa** [comment]
@DaveMurchison83 I'm closing it, reopen it again in case.
